### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by akanmuratcimen** [waldner/Firefox-RunWith#3]
I'm getting the following error after I reinstall my OS:

Console logs:
```
Loaded configuration is {"config":{"conf":[{"id":"0","title":"test","nmhost":"runwith","contexts":["link"],"documentUrlPatterns":["<all_urls>"],"targetUrlPatterns":["<all_urls>"],"action":["firefox"],"shell":false,"wait":true}]}} background.js:142:13
targetUrlPatterns <all_urls> background.js:76:13
Menu item created, id 0 background.js:92:13
Setting options done, result is: 0 background.js:144:13
About to run: {"cmd":["firefox"],"shell":false,"wait":true} background.js:50:11
NM Error:  Error: An unexpected error occurred background.js:22:11
```
Debugging screenshot:
![image](https://github.com/waldner/Firefox-RunWith/assets/1022626/0b39b743-f24d-4398-9f52-3179d95f56d0)

My spec:
XFCE on Debian 12

It was working well before I reinstall the OS. Do I need to install something else?
Thanks.

**Comment by waldner** [comment]
Interesting. Let me see if I can reproduce it with the info you provided (I'm assuming you have `runwith.py` in place, of course).

**Comment by akanmuratcimen** [comment]
Yes, I'm using `runwith.py` and I haven't made any changes to it. I just configured the path in `runwith.json` and set the necessary permissions.

**Comment by waldner** [comment]
Yes, I've just reproduced the problem. Let me see what it is.

**Comment by akanmuratcimen** [comment]
Yes, both ways fixed the issue. Thank you so much for this great add-on and quick response.
